### ISSUE TITLE
ImageStreamCompleter._checkDisposed fails in production app

### ISSUE THREAD

**Issue by LucasG04** [LucasG04/foodly_app#177]
Crashlytics catches an error several times lately when loading images which causes the app to crash. The reason for this error seems to be this: https://github.com/Baseflow/flutter_cached_network_image/issues/785

There is already a solution that needs to be applied: https://github.com/Baseflow/flutter_cached_network_image/pull/777

Adjust `pubspec.yaml` like this:
```yaml
  cached_network_image:
    git:
      url: https://github.com/SuaMusica/flutter_cached_network_image.git
      ref: feature/errorListener
      path: cached_network_image

```
